Asignaturas = []
#"Matemáticas", "Química", "Historia", "Lengua"
Grades = []
x=1

print("---------------------------------------------")
print("Bienvenido al sistema de Notas & Asignaciones")
print("              By AllanDev")
print("---------------------------------------------")
while x==1:
    print("--------------------------------------------")
    print("  Ingrese la Asignatura que desea agregar.")
    print("--------------------------------------------")
    clase= input()
    Asignaturas.append(clase)
    print("--------------------------------------------")
    print("Ingrese la nota que obtuvo en la Asignatura")
    print("--------------------------------------------")
    grade= int(input())
    Grades.append(grade)

    print("--------------------------------------------")
    print("  ¿Desea agregar otra Asignatura y Nota?")
    print("--------------------------------------------")
    print("               SI= 1 | NO=2       ")
    print("--------------------------------------------")
    x= int(input())
    print("--------------------------------------------")

else:
    if len(Asignaturas)==1:
        if Grades[0]>=60:
            print("Su calificación en "+ Asignaturas[0]+" es:")
            print(Grades[0])
            print("ESTATUS: APROBADO")
        else:
            print("Su calificación en "+ Asignaturas[0]+" es:")
            print(Grades[0])
            print("ESTATUS: REPROBADO")
    else:
        if len(Asignaturas)==2:
            if Grades[1]>=60:
                print("Su calificación en "+ Asignaturas[0]+" es:")
                print(Grades[0])
                print("ESTATUS: APROBADO")
                print("Su calificación en "+ Asignaturas[1]+" es:")
                print(Grades[1])
                print("ESTATUS: APROBADO")
            else:
                print("Su calificación en "+ Asignaturas[0]+" es:")
                print(Grades[0])
                print("ESTATUS: REPROBADO")
                print("Su calificación en "+ Asignaturas[1]+" es:")
                print(Grades[1])
                print("ESTATUS: REPROBADO")
        else:
            if len(Asignaturas)==3:
                if Grades[2]>=60:
                    print("Su calificación en "+ Asignaturas[0]+" es:")
                    print(Grades[0])
                    print("ESTATUS: APROBADO")
                    print("Su calificación en "+ Asignaturas[1]+" es:")
                    print(Grades[1])
                    print("ESTATUS: APROBADO")
                    print("Su calificación en "+ Asignaturas[2]+" es:")
                    print(Grades[2])
                    print("ESTATUS: APROBADO")
                else:
                    print("Su calificación en "+ Asignaturas[0]+" es:")
                    print(Grades[0])
                    print("ESTATUS: REPROBADO")
                    print("Su calificación en "+ Asignaturas[1]+" es:")
                    print(Grades[1])
                    print("ESTATUS: REPROBADO")
                    print("Su calificación en "+ Asignaturas[2]+" es:")
                    print(Grades[2])
                    print("ESTATUS: REPROBADO")
            else:
                if len(Asignaturas)==4:
                    if Grades[3]>=60:
                        print("Su calificación en "+ Asignaturas[0]+" es:")
                        print(Grades[0])
                        print("ESTATUS: APROBADO")
                        print("Su calificación en "+ Asignaturas[1]+" es:")
                        print(Grades[1])
                        print("ESTATUS: APROBADO")
                        print("Su calificación en "+ Asignaturas[2]+" es:")
                        print(Grades[2])
                        print("ESTATUS: APROBADO")
                        print("Su calificación en "+ Asignaturas[3]+" es:")
                        print(Grades[3])
                        print("ESTATUS: APROBADO")
                    else:
                        print("Su calificación en "+ Asignaturas[0]+" es:")
                        print(Grades[0])
                        print("ESTATUS: REPROBADO")
                        print("Su calificación en "+ Asignaturas[1]+" es:")
                        print(Grades[1])
                        print("ESTATUS: REPROBADO")
                        print("Su calificación en "+ Asignaturas[2]+" es:")
                        print(Grades[2])
                        print("ESTATUS: REPROBADO")
                        print("Su calificación en "+ Asignaturas[3]+" es:")
                        print(Grades[3])
                        print("ESTATUS: REPROBADO")
                else:
                    if len(Asignaturas)==5:
                        if Grades[4]>=60:
                            print("Su calificación en "+ Asignaturas[0]+" es:")
                            print(Grades[0])
                            print("ESTATUS: APROBADO")
                            print("Su calificación en "+ Asignaturas[1]+" es:")
                            print(Grades[1])
                            print("ESTATUS: APROBADO")
                            print("Su calificación en "+ Asignaturas[2]+" es:")
                            print(Grades[2])
                            print("ESTATUS: APROBADO")
                            print("Su calificación en "+ Asignaturas[3]+" es:")
                            print(Grades[3])
                            print("ESTATUS: APROBADO")
                            print("Su calificación en "+ Asignaturas[4]+" es:")
                            print(Grades[4])
                            print("ESTATUS: APROBADO")
                        else:
                            print("Su calificación en "+ Asignaturas[0]+" es:")
                            print(Grades[0])
                            print("ESTATUS: REPROBADO")
                            print("Su calificación en "+ Asignaturas[1]+" es:")
                            print(Grades[1])
                            print("ESTATUS: REPROBADO")
                            print("Su calificación en "+ Asignaturas[2]+" es:")
                            print(Grades[2])
                            print("ESTATUS: REPROBADO")
                            print("Su calificación en "+ Asignaturas[3]+" es:")
                            print(Grades[3])
                            print("ESTATUS: REPROBADO")
                            print("Su calificación en "+ Asignaturas[4]+" es:")
                            print(Grades[4])
                            print("ESTATUS: REPROBADO")
                    else:
                        if len(Asignaturas)==6:
                            if Grades[5]>=60:
                                print("Su calificación en "+ Asignaturas[0]+" es:")
                                print(Grades[0])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[1]+" es:")
                                print(Grades[1])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[2]+" es:")
                                print(Grades[2])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[3]+" es:")
                                print(Grades[3])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[4]+" es:")
                                print(Grades[4])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[5]+" es:")
                                print(Grades[5])
                                print("ESTATUS: APROBADO")
                            else:
                                print("Su calificación en "+ Asignaturas[0]+" es:")
                                print(Grades[0])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[1]+" es:")
                                print(Grades[1])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[2]+" es:")
                                print(Grades[2])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[3]+" es:")
                                print(Grades[3])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[4]+" es:")
                                print(Grades[4])
                                print("ESTATUS: APROBADO")
                                print("Su calificación en "+ Asignaturas[5]+" es:")
                                print(Grades[5])
                                print("ESTATUS: REPROBADO")
print("-----------------------------------")
